env:
  browser: true
  es2021: true
extends:
   - airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console:
    ["error", { allow: ["clear", "group", "groupEnd", "info", "warn", "error", "log"] }],
  radix:
    ["error", "as-needed"],
  func-names:
    ["error", "never"],
  no-unused-vars:
    "off",
  no-undef:
    "off",
  no-param-reassign:
    "off",
  no-underscore-dangle:
    "off",
  no-use-before-define:
    "off",
  no-shadow:
    "off",
  no-restricted-syntax:
    "off",
  no-await-in-loop:
    "off",
  eqeqeq: 
    "error"
}